---
title: "ds202_lab2_team"
author: "Evan Mills, Max Farver"
date: "February 5, 2019"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
choco <- read.csv("https://xdaiisu.github.io/ds202materials/hwlabs/choco.csv")
head(choco)
```
1.)
```{r}
sum(!is.na(choco$Rating))
```

2.)
```{r}
ggplot(choco, aes(x=Review.Date)) + geom_histogram(binwidth = 1)
```

3.)
```{r}
top_3 <- choco %>% 
  group_by(Company.Location) %>%
  tally(sort = TRUE)
top_3 <- top_3 %>% top_n(3)
top_3

top_3_data <- filter(choco, Company.Location %in% c('U.S.A.', 'France', 'Canada'))

ggplot(data = top_3_data, aes(x=Company.Location, y=Rating)) + 
  geom_boxplot()
```

Ratings are fairly even across the company's locations, though the USA and France have a few errant low rating. The median of the ratings is nearly identical.

4.)
Is there a correlation between the review date and the rating?

5.)
```{r}
plot(choco$Review.Date, choco$Rating, xlab="Review Date", ylab="Rating", main = "Rating vs Date")
```

As you can tell from the graph above there is no correlation between the date that the chocolate bar was rated and the rating given.